### ISSUE TITLE
[QUESTION] UI broken

### ISSUE THREAD

**Issue by HK0106** [tsedio/tsed-formio#133]
![image](https://github.com/tsedio/tsed-formio/assets/63858332/bad06703-4803-4666-8286-0f4b9102b80a)
![image](https://github.com/tsedio/tsed-formio/assets/63858332/7e8234f4-6b30-4948-9e49-e47344434517)

My screen after running project

please let me know why i got this issue?

nodejs: v18.18.2
npm: 9.8.1
yarn: 1.22.19
typescript: 5.2.2

**Comment by Romakita** [comment]
Have you imported the library styling  and tailwind ?
Look this file: https://github.com/tsedio/tsed-example-formio/blob/master/packages/backoffice/src/index.tsx#L3

See you

**Comment by Romakita** [comment]
Ok the readme describe only the library installation, but as you know, formio you support many css framework (bootstrap, material, etc...). If you bring to use tailwind look the readme here:
https://github.com/tsedio/tsed-formio/blob/master/packages/tailwind-formio/readme.md

**Comment by HK0106** [comment]
Thanks its work! 
Can i using form.io json for embeded component

**Comment by Romakita** [comment]
I don’t know ^^
