### ISSUE TITLE
Icons are not displaying in Ionic Angular application

### ISSUE THREAD

**Issue by shyamalaUnv** [tsedio/tsed-formio#134]
I have installed using these commands in ionic angular application
```
npm install @tsed/tailwind-formio --save
npm install --save-dev postcss-nested@4
```

and imported these css class in global.scss
```
@import "~tailwind.css";
@import "~@tsed/tailwind-formio/styles/index.css";
```

In component using like this
```
import tailwind from "@tsed/tailwind-formio";
Formio.use(tailwind);
Templates.framework = "tailwind";
```

form is loading but icons are not displaying 
![Screen Shot 2023-11-29 at 3 52 10 PM](https://github.com/tsedio/tsed-formio/assets/57700307/68fe3a8d-2a4e-4a98-adf8-fd5c87f9fec1)

Can anyone help me on this?

**Comment by Romakita** [comment]
Form the readme:

Optionally, you can import fonts and icons:

```diff
@import "~formiojs/dist/formio.full.css";
@import "./tailwind.css";
+@import "./fonts/source-sans-pro/index.css";
+@import "./fonts/inconsolata/index.css";
+@import "./fonts/bxicons/index.css";
@import "~@tsed/tailwind-formio/styles/index.css";
```
