### ISSUE TITLE
how can i use with this to angular - tailwind project 

### ISSUE THREAD

**Issue by skandula106** [tsedio/tsed-formio#48]
I have to use this with angular form-io along tailwind css can you help me with this

**Comment by Romakita** [comment]
I don't know. I don't use angular + tailwind. The principle should be the same, follow the guide install for tailwind + angular. You can found this tutorial on google.

The steps described in this readme https://github.com/tsedio/tsed-formio/blob/master/packages/tailwind-formio/readme.md
should be the same things with angular.

you'd just have to add theses lines in the app.ts or main.ts or index.ts of your angular app:
```typescript
import { Formio, Templates } from "@tsed/react-formio";
import tailwind from "@tsed/tailwind-formio";

Formio.use(tailwind);
Templates.framework = "tailwind";
```

See you

**Comment by skandula106** [comment]
![image](https://user-images.githubusercontent.com/58414973/147357106-170ab12c-e602-4a2f-82f7-66dd5db79238.png)

**Comment by Romakita** [comment]
import { Formio, Templates } from "formio.js";

**Comment by dinbtechit** [comment]
@skandula106  - Did you get it working for angular?

**Comment by dinbtechit** [comment]
Just curious... does tsed/formio support dynamic css? for e.g., `w-[50em]`

This css does not seem to be applying. Is this an expected behaviour?

![image](https://github.com/tsedio/tsed-formio/assets/17984781/357b9cfe-3e0b-4d2e-8896-76a96b9db141)
