### ISSUE TITLE
[QUESTION] Access to the formController

### ISSUE THREAD

**Issue by jpstijn** [tsedio/tsed-formio#49]
Hi,

I saw that there was a question asked here 4 days ago so thats why i thought maybe i could ask for help as well. I would like to fire validation on a form from an button outside the form itself. When looking at the formio documentation i thought i could use the formController to do this. 

![image](https://user-images.githubusercontent.com/24881734/147555114-8e5561a6-ea19-4f52-ac95-30b68626873f.png)

But i cant seem to find a way to retrieve the form controller when rendering my form in this way:
`<form  form={formContent} />`

**Comment by Romakita** [comment]
Hello @jpstijn 

You can retrieve the formio instance by listening the onFormReady event:

```typescript
import {Form as FormFormio} from "formiojs";
import {Form} from "@tsed/react-formio";

<Form onFormReady={(formio: FormFormio) => {   } />
```

See you :)

**Comment by Romakita** [comment]
This PR improve the typings #50 for the onFormReady event :)
