### ISSUE TITLE
Tailwind 3.x support

### ISSUE THREAD

**Issue by anorborg** [tsedio/tsed-formio#56]
## Informations
**Is your feature request related to a problem? Please describe.**
I tried getting this setup following the instructions and hit an error related to this:
https://github.com/tailwindlabs/tailwindcss/pull/4666

which now has tailwindcss throw when trying to `@apply` the `group` class. There appears to be additional incompatibilities as well. Using TailwindCSS 2.x seems to work fine.

**Describe the solution you'd like**
Support TailwindCSS 3.x

**Comment by afraazali** [comment]
I’m currently using https://github.com/NIT-Administrative-Systems/dynamic-forms, and was wondering if it would be possible to have this plugin work for laravel + tailwind 3?

I figure there will need to a laravel/blade template created that uses tailwind classes instead of bootstrap

**Comment by Romakita** [comment]
The library support tailwind 3 also :)
